### ISSUE TITLE
charts app problems

### ISSUE THREAD

**Issue by khedersyria** [adam-cowley/epitome#41]
Hi Mr @adam-cowley 
I am kheder from Syria. I am new in neo4j and I tried to use charts App to build query visualy but it does not work correctly. when I enetred query builder section the charts app does not show me any node or edge which I can select from them to start my first visual query. Can you help me please.
![Capture2](https://github.com/neo4j-labs/charts/assets/126420061/7350c7ef-ec42-40f4-b6eb-add8bb9dcd6d)
![Capture](https://github.com/neo4j-labs/charts/assets/126420061/8a531816-2566-4b0b-91c2-1c74d9ce2ef1)
![Capture1](https://github.com/neo4j-labs/charts/assets/126420061/078e8150-44fd-49ed-83fa-ce140f0d7ebc)

**Comment by khedersyria** [comment]
I found the solution it required to install apoc plugin to neo4j

**Comment by adam-cowley** [comment]
Hey Kheder! I'm glad you found the solution.  I would strongly recommend using [Neodash](https://neo4j.com/labs/neodash) over Charts, because it is in active development.

**Comment by khedersyria** [comment]
Thank you very much Mr @adam-cowley
